# [theme]
# base = "dark"
# primaryColor = "#E694FF"
# backgroundColor = "#0E1117"
# secondaryBackgroundColor = "#262730"
# textColor = "#FAFAFA"
# font = "sans serif"

[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
