[connections.postgresql_local]
dialect = "postgresql"
host = "localhost"
port = "5432"
database = "ap_collection"
schema = "public"
username = "postgres"
password = "postgres"

[connections.postgresql_production]
dialect = "postgresql"
host = "postgres.railway.internal"
port = "5432"
database = "ap_collection"
schema = "public"
username = "postgres"
password = "jOSeFhaRSMphbmbusEibgOuRWfULlBju"
